name: 'Spectral comment'
description: 'Comments pull requests with Spectral linter outputs'
inputs:
  github-token:
    description: 'Github token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
