openapi: 3.0.1
info:
  title: Sample
  contact:
    name: REST API
    email: sepectral-comment-action@noreply.com
    url: https://github.com/spectral-comment-action/issues/new
  version: 0.0.1
tags:
- name: greetings
  description: Server greets client
paths:
  /helloWorld:
    $ref: './paths/greetings.yml#/greetings'
  /foobar:
    $ref: './paths/foobar.yml#/foobar'
components:
  schemas:
    Greeting:
      $ref: './schemas/greetings.yml#/greeting'

