name: "test-action"
on:
  pull_request:

jobs:
  test:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # (optional) set the node version if you do not want to use the one specified in Github environment
    # see Software installed on GitHub-hosted runners
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - id: lint
      env:
        OAS_PATH: sample/spec/openapi.yml
      run: |
        npx @stoplight/spectral@5.1.0 lint $OAS_PATH -f json -q -F error > spectral-lint-results.json
        echo "::set-output name=spectral-lint-results::$(cat spectral-lint-results.json)"
    - uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        spectral-lint-results: ${{ steps.lint.outputs.spectral-lint-results }}

